### ISSUE TITLE
Update ncwms configurator documentation

### ISSUE THREAD

**Issue by corviday** [pacificclimate/modelmeta#102]
The documentation for the ncWMS configurator has gotten out of date, and I'm not sure how to run it.

``` bash
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install -r requirements.txt -i https://pypi.pacificclimate.org/simple/
$ pip install .
$ ncwms_configurator python scripts/ncwms_configurator -d ELIDED -e all_files -o all_files20200827.xml create
### Creating modelmeta ORM
INFO:ncwms_configurator:Using dsn: ELIDED
INFO:ncwms_configurator:Writing to file: all_files20200827.xml
INFO:ncwms_configurator:Formatting for ncWMS version 2
Traceback (most recent call last):
  File "/home/lzeman/tmp/mm/modelmeta/venv/bin/ncwms_configurator", line 43, in <module>
    args.func(args)
  File "/home/lzeman/tmp/mm/modelmeta/venv/lib/python3.6/site-packages/ncwms_configurator/__init__.py", line 189, in create
    sesh = get_session(args.dsn)
  File "/home/lzeman/tmp/mm/modelmeta/venv/lib/python3.6/site-packages/ncwms_configurator/__init__.py", line 179, in get_session
    engine = create_engine(args.dsn)
NameError: name 'args' is not defined

$ python scripts/ncwms_configurator -d ELIDED -e all_files -o all_files20200827.xml create
### Creating modelmeta ORM
INFO:ncwms_configurator:Using dsn: ELIDED
INFO:ncwms_configurator:Writing to file: all_files20200827.xml
INFO:ncwms_configurator:Formatting for ncWMS version 2
Traceback (most recent call last):
  File "scripts/ncwms_configurator", line 43, in <module>
    args.func(args)
  File "/home/lzeman/tmp/mm/modelmeta/venv/lib/python3.6/site-packages/ncwms_configurator/__init__.py", line 189, in create
    sesh = get_session(args.dsn)
  File "/home/lzeman/tmp/mm/modelmeta/venv/lib/python3.6/site-packages/ncwms_configurator/__init__.py", line 179, in get_session
    engine = create_engine(args.dsn)
NameError: name 'args' is not defined
```

**Comment by jameshiebert** [comment]
That looks more like a *bug* than simply a documentation problem.
